name: Fly Deploy

# Only trigger, when the build workflow succeeded on main
on:
    workflow_run:
        workflows: ["Rust CI workflow"]
        types:
            - completed
        branches:
            - main

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
